### ISSUE TITLE
Remove duplicate static files

### ISSUE THREAD

**Issue by VahidGh** [openworm/ChannelWorm#140]
With the latest updates to UI, now we have two static directories with the same content under [wsgi](https://github.com/openworm/ChannelWorm/tree/master/channelworm/wsgi/static), and related directories for each app (digitizer, web_app, ec).

**Comment by miladjafary** [comment]
@VahidGh I only see one static directory under wsgi directory. and there is not any duplicate static file. 
would you please expelling more?

**Comment by VahidGh** [comment]
@miladjafary, e.g. [this](https://github.com/openworm/ChannelWorm/tree/master/channelworm/wsgi/static/digitizer) and [this](https://github.com/openworm/ChannelWorm/tree/master/channelworm/digitizer/static/digitizer)

**Comment by miladjafary** [comment]
@VahidGh  I think it's because of "collectstatic" command. 
May be in production env, we can delete static folders from app directory.

**Comment by VahidGh** [comment]
I see. I guess we should use `-link` to prevent creation of those files in the wsgi directory (creating symbolic link instead). Would you please check which one is not required and then remove unnecessary ones?

**Comment by miladjafary** [comment]
Sure , I will do it

**Comment by rgerkin** [comment]
@VahidGh @miladjafary Typically "collectstatic" is run only in production, because in production your static files are only served from one place, served by Apache or Nginx or whatever.  In testing locally, the django test server can just serve them from the app directories.  And so your staticfiles directory list should have the production location listed first (which will be ignored in local testing), and then the app directory locations next (or rather the staticfiles module that refers to the app directories).

**Comment by VahidGh** [comment]
@rgerkin, Right. thanks for your comment.
