### ISSUE TITLE
Unit testing of ion channels: candidate data for building tests

### ISSUE THREAD

**Issue by rgerkin** [openworm/ChannelWorm#183]
From the data curated [here](http://channelwormdjango-channelworm.rhcloud.com/ion_channel/graph/), does anyone have any thoughts about which would be the best basis for the next few SciUnit tests?  Considerations are: relevance to the model, orthogonality to previous tests, quality of data, etc.

**Comment by VahidGh** [comment]
In my opinion the SLO-2 channel would be the best candidate for the next model generation and testing process. This channel has an important role in neuromuscular junctions in C. elegans, so we can start working on modeling channels in motorneurons.
[This paper](http://www.nature.com/ncomms/2014/141010/ncomms6155/full/ncomms6155.html) is a good reference, regarding this issue.

**Comment by rgerkin** [comment]
@VahidGh I've added an IV Curve test for the SLO-2 channel [here](https://github.com/openworm/ChannelWorm/blob/dev/tests/sciunit/SLO-2_IV.ipynb), although you can see that the model/data agreement is pretty bad, compared to the EGL-19 channel shown [here]((https://github.com/openworm/ChannelWorm/blob/dev/tests/sciunit/SLO-2_IV.ipynb).  I'm using Fig. 7B from 10.1113/jphysiol.2010.200683 for the data; which is the first entry that comes up in the channelworm DB; should I be using a different set of data?

**Comment by VahidGh** [comment]
@rgerkin: Regarding scaling, I think considering some common expression system such as `Xenopus Oocytes`, `HEK`, or `CHO` cells would bring a built-in scaling system, automatically.

Fig. 7B from 10.1113/jphysiol.2010.200683, would be great when combining other channels and considering motoneuron cells in c. elegans. I guess it would be better to start with fig. 6a from 10.1038/77670 (or just figure ID=5, something like [this](https://github.com/openworm/ChannelWorm/blob/dev/channelworm/fitter/examples/EGL-36.py) new approach), as it is expressed and clamped lonely in `Xenopus Oocytes`. 

I have also started some work for this channel [here](https://github.com/openworm/ChannelWorm/blob/dev/channelworm/fitter/examples/SLO-2.py), and generated some initial model [here](https://github.com/openworm/ChannelWorm/blob/dev/models/SLO-2.channel.nml) using a fixed time-course (which is now possible to optimize it using a dynamic time-course using the most recent version of cwFitter). Although, the model generates the same I/V curve as shown in the paper, however, in order to build a precise model, encountered some problem due to having to consider [Cl], and didn't know how should I consider concentrations other than [Ca] using NeuroML/NEURON.

**Comment by rgerkin** [comment]
@VahidGh I've added a notebook for SLO-2 [here](https://github.com/openworm/ChannelWorm/blob/dev/tests/sciunit/SLO-2_IV.ipynb).  Things look bad for the model at the moment.  Can you identify any issue in the model I am using in that notebook?  

I've addressed scaling by auto-scaling the model output (by a constant) to match the data, since we have not only one but two degrees of freedom we can do nothing about (one is the surface area of the cell, and the other is the bulk conductance of the channels on the patch).  This works fine for EGL-19, but for SLO-2 I had to turn it off because the model-data agreement is so bad the scaling algorithm wanted to reverse the sign of the model output!

**Comment by VahidGh** [comment]
@rgerkin, What do you mean by > Things look bad for the model ?
If you mean the `Predicted (model)` curve, I couldn't find the way it is generated by within the notebook!

**Comment by rgerkin** [comment]
@VahidGh Yes, I mean things look bad for the `Predicted (model)` curve.  The model is being run inside of the `judge` method of the `sciunit.Test` I instantiate in that notebook.  I presume if you run it any other way you will get the same result.  For [EGL-19](https://github.com/openworm/ChannelWorm/blob/dev/tests/sciunit/EGL-19_IV.ipynb) I don't get something so horrific, although even there the agreement isn't great.
