### ISSUE TITLE
Which parameters will be used for fitting?

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#43]
It looks like NeuroTune will be sufficient for our purposes of tuning the ion channel models towards their observed counterparts.

Since there may be multiple sorts of validation tests beyond IV curve comparison, we should talk about which parameters will be tuned on the ion channels.

Parameters that are intrinsic to the ion channel model itself are eluding me, since so much of their kinetics is determined by their context.

**Comment by VahidGh** [comment]
@travs, these are parameters I'm currently playing with:

'g', 'e_rev', 'v_half_a', 'v_half_i', 'k_a', 'k_i', 'T_a', 'T_i', 'a_power', 'i_power'

In addition to these parameters in case of modeling Calcium channels:
'ca_half_i','alpha_ca','k_ca','T_ca','cdi_power'

Some challenges are:
1) Whether to use g_dens instead of g and including C_mem in the parameters?
2) Is there a better way to guess a/i powers (for activation/inactivation expressions) than evolving these parameters with e.g. min-max of 0-4? 
3) For activation/inactivation expressions, I'm now simply using `1/(1+ exp ((v_half - v) / k))` , but it is possible to include other coefficients in this expression.

Actually, the Optimizer class from the Neurotune package is useful for our purposes, and we need other functions for the evaluation and cost measurements, which I'm working on. 
Currently I'm comparing and mixing 2 other approaches taken from relevant papers with Neurotune for implementing the fitter+optimizer.

**Comment by travs** [comment]
@vahidgh

Is this still in progress? If there are any sub-issues let's raise those separately, and let me know if there's anything I can do to help! :)

**Comment by VahidGh** [comment]
@travs,  This would be open, unless we have the first working/validated model. especially for the 3rd challenge mentioned above :)

**Comment by travs** [comment]
@VahidGh You were discussing some changes in ChannelWorm at the hackathon; do you think you have a good idea of what the activation/inactivation parameters you will be using are?

**Comment by VahidGh** [comment]
I could fit data to models using voltage-/ion- dependent activation/inactivation parameters.
The above mentioned parameters in addition to ion dependent ones for some channels were OK.
We may use some more appropriate names, if decided to generate fixed schemes for PyOW.
