### ISSUE TITLE
Decide on cost function/evaluation to apply when comparing I/V curves

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#52]
We need some metric that returns a single value indicating how well a particular modeled I/V curve fits the expected observed I/V curve.

@VahidGh mentions:
>In my implementations, I've considered the cost function for evaluating I/V cures, as sum of the squared distances between the sample and simulated points divided by the number of points and trying to minimize this.
I was thinking about storing a normalized version of this measurement and comparing with other models.
How is this different from the approach is going to be taken by the SciUnit?

What statistics should we apply in order to get this value?

*Note that this is of lower priority than implementing a placeholder cost function that works*

**Comment by rgerkin** [comment]
Much of the content of the Evaluator class [here](https://github.com/VahidGh/ChannelWorm/blob/cwFitter/cwFitter/Evaluator.py can be placed inside the sciunit Test method "compute_score", first by just using the Evaluator class as written and instantiating and calling it in compute_score, and returning its result, and eventually by refactoring it for SciUnit.  

SciUnit at one time had a Comparator class that was much like Evaluator, but we weren't sure how to generalize it across disciplines, so now implementation of evaluation/comparison is pretty open-ended, so long as it is inside compute_score.

**Comment by rgerkin** [comment]
In [this](https://github.com/VahidGh/ChannelWorm/blob/tests/tests/IVCurve_Model.ipynb) notebook, in cells 20-22 you can see the implementation of simple cost function, which takes the sum of the squared difference between the observed and predicted IV Curves, after first interpolating them at 1 mV intervals.  The agreements between the curves is currently terrible, which must be due to either a problem with the model, the way I am running it, or perhaps I am comparing the wrong model to the data.

**Comment by VahidGh** [comment]
@rgerkin, good points, thank you. I also was thinking about the distance measurements. And working on some TODOs regarding these issues (assuming it's not only the I/V curves being used, and in the near future other curves such as I/t , V/t, G/V, m/t, h/t, etc are going to be used):

* How to normalize this function in order to cover all these curves in a way that results from each curve evaluation could be comparable with others. here we need also some metrics to make the result from each curve comparable with others. 
* How to better weight each evaluation to consider importance of that curve in the overall result
* How to improve the distance measurement. For example measuring the area between two curves maybe have a better result than the existing point-based measurement, as there is usually some limited points in the digitized samples.

Finally it would be nice to specialize and improve each package by interchanging some code between them (something I have in mind while coding), but for now the priority to have something that works ASAP, forcing me to integrate these codes in one place. For example some limitations such as unit conversion, accessing to some parameters that usually is being used by jnml while simulating, but is not possible, or I don't how to have access after simulation, reducing the run-time for a heavy optimization process, and also "learning how things work :)" makes me to re-code some (maybe existing) codes.
Anyway, I'm really interested in standardization and specialization of these packages as discussed before, and definitely will spend some time to put each peace of code in the right place. I appologize on behalf of myself if there is some hypoactivity regarding this issue at this time :)

**Comment by travs** [comment]
Hey @VahidGh, how is this one going; can we still consider it "in progress"?

Also, are there any sub-issues we can create cards for, or anything else I can help with?

**Comment by VahidGh** [comment]
In the cwFitter side, I've considered a field in our data model to store the final fitness/score when a model is built. thanks to @pgleeson, it is possible from Neurotune side. 
Right now it is dependent on the y axis (e.g. A/pA for I/V or VClamp and V/mV for IClamp, etc). But a better option would be a normalized one (some unit-independent distance measurement).

**Comment by travs** [comment]
@VahidGh Ok, so should we close this issue here, and raise it in the relevant Neurotune fork instead? That is, unless I am misunderstanding.

**Comment by VahidGh** [comment]
@travs, the cost value being calculated in the cwFitter, and the best one returns by Neurotune. So it is still open in cwFitter side.

**Comment by travs** [comment]
@VahidGh Given the progress you were discussing during the hackathon, are you fine with the cost function you ended up choosing?

**Comment by VahidGh** [comment]
@travs, For I/V curves, yes, but as discussed before, in order to be able
to include other kind of curves, we have to normalize all cost values,
which is the case I'm currently working on...

**Comment by VahidGh** [comment]
OK, we can consider the cost values based on the mean square distance of Y axis for the same plots. E.g. pA^2 for I/V or V/t plots.

For comparing plots with different scales. I've considered constraints in the GA and PSO implementations in cwFitter. For example if there is an experiment which has a G/Gmax / V (instead of I/V) and a VClamp, then considering 1e-4 as minimum acceptable of mean square distance for G/Gmax / V plot (as the Y axis is in range of 0-1), parameters that pass this constraint could be compared for V/t, and again the final error is based on pA^2.

I'm also going to keep the cost value for each plot comparison along with the model, for further validations.
