### ISSUE TITLE
Create UI for curation process

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#91]
This will include authentication, data viewing, and export button (which calls "export" function, that is not yet written).

**Comment by miladjafary** [comment]
@travs @VahidGh according to chat ,  I think we can handle the syncing CW and pyow in the business logic of crud and overide  in model code .
I am not sure , but if it possible,  it could be better than have and export function and handle it manually by the User.

The syncing  step could be this : 
1-  user add an entity in CW throughout  UI. (Experiment  , patch-clamp , ....)
2-  django  save the model object (also saveing method on the model was overide for calling PyOW adapter)
3- if saving in django model was successful,  PyOW adapter could be call for syncing PyOW  db)
4- if saving on PyOW was unsuccessful,  delete object from CW  and throw an exception  (it's could be optional step)


In this way we don't need UI for handeling sync DB.
Let me know If I am wrong about this task

**Comment by VahidGh** [comment]
@miladjafary, This curation step is not exactly the same process as we discussed before.
Here the point is that someone who is allowed to curate a model manually (maybe after some automatic validation process), decides whether a model is accurate enough to be shared with the scientific community. Then he/she decides to flag that model as "curated".
In long-term, this process should be integrated with some feature from the PyOW that allows someone to send a CRUD request to the main PyOW DB. But as this is not yet available, we keep storing data within our DB and will import those needed to the PyOW DB when available.
But in order to make this process easy and "stable", the best solution would be to agree on the scheme for needed objects on both sides, to easily share (import/export) data between them (assuming this is not just CW which Does CRUD, and different users or even different versions/instances of CW may do this).

This is for the curation process, but regarding the data entry, we can keep go on based on Django models, but considering some scheme which is defined and accepted by the PyOW requirements, specially AT THIS TIME that the data entry process has not begun.

I believe, this would be the easiest and the safest approach, IF we agree on "what kind of data" and "in which format", does PyOW need to store. So, would great if @slarson, could help us on the final decision :)

**Comment by slarson** [comment]
Hi guys, I think we need a diagram on the curation process that has a block for the CW app, a block for PyOpenWorm and maybe a flow diagram with questions to determine when something goes into PyOpenWorm.  What are the questions we would ask for when something goes in and when it stays out?

As for contents, I would think that the data model consisting of experiment, channel info, channel model info, and pointers to figures within papers would be reasonable, but apologies if I'm a bit behind on the conversation.

**Comment by travs** [comment]
@VahidGh Agreed. I am starting to define the schema for these data models in PyOpenWorm right now. In our meeting today we can discuss the parameters we want a bit further, and I can incorporate those into my changes in PyOW.

@slarson Also agreeing here; we need some sort of defined protocol for a curator to follow when this UI is available.

**Comment by travs** [comment]
@VahidGh @miladjafary You guys have made significant progress on this. You this we can close this now?

**Comment by miladjafary** [comment]
@travs  if it's just related to Authentication ,yes . we can close it :D

**Comment by travs** [comment]
@miladjafary Ok right, I think there were 3 parts:
- [x] authentication
- [x] data viewing
- [ ] exporting
