### ISSUE TITLE
Write an Export function that saves data from ChannelWorm to PyOpenWorm

### ISSUE THREAD

**Issue by travs** [openworm/ChannelWorm#92]
This will be a facade that calls the adapter classes going from CW to PyOW.

**Comment by pgleeson** [comment]
Sorry for raising this again, but this is the type of thing that worries me... The contents of PyOpenWorm should be curated, stable, well tested & trustable. I'm fine with some of the contents relating to models if they're clearly marked as such, rather than published literature, but there certainly shouldn't be a quick & easy route for contents added via a web app to get into the core of PyOpenWorm without thorough checking (apologies if I'm reading too much into this).

Essentially my point is if this type of modelling/channel fitting data is generated by ChannelWorm, why doesn't it stay part of ChannelWorm (i.e. distributed as part of this repo)? It can reuse the core PyOpenWorm infrastructure/classes & a user can ask the latest ChannelWorm library for the latest version of channel X on cell Y rather than putting it in PyOpenWorm...

**Comment by VahidGh** [comment]
@pgleeson, Good points, thanks for clearing this.
I reefer to #91 for more details. also we had some chats after this issue. I think now we are agreed on what your concern is.

**Comment by slarson** [comment]
@pgleeson we're versioning the contents of PyOpenWorm so there won't be data updates until they are first examined on a branch and a pull request gets issued.  On top of that there is a curation process implied between ChannelWorm and pushes into PyOW that is being worked out.

**Comment by travs** [comment]
@pgleeson This is of course a valid concern. Given the versioning and curation @slarson mentions, I think it is still possible to write this export function now, and not make use of it until we've decided how to handle modelling information alongside other information in PyOW. 

If we go this route, this can be rephrased as a  question of data access in PyOpenWorm: how can we appropriately separate the APIs used for accessing non-modelling and modelling data?

**Comment by pgleeson** [comment]
Ok, glad to see you're thinking about potential issues with this too.

**Comment by travs** [comment]
Starting this today
